name: frontned
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage: ^5.0.2
  dio: ^5.0.0
  shared_preferences: ^2.0.17
  google_fonts: ^5.0.0
  image_picker: ^0.8.6
  # flutter_neumorphic: ^3.2.0 # This dependency is removed as per your instructions

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ # Ensure assets directory is correctly referenced without leading slash